#pragma once

#include <windows.h>
#include <stdio.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <iphlpapi.h>
#include <winternl.h>
#include <ntstatus.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <system_error>
#include <thread>
#include <vector>
#include <unordered_map>
#include <optional>
#include <iomanip>
#include <map>
#include <random>
#include <list>
#include <utility>
#include <atomic>
#include <mutex>
#include <future>
#include <any>